## Coronavirus

In [148]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt

In [7]:
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_excel('Coronavirus.xlsx')

In [4]:
data.set_index('Date')

CoronavirusCasesWorld  CoronavirusDeathsWorld  Death rate
Date                                                                 
2020-01-22                    332                       0         NaN
2020-01-23                    555                       0         NaN
2020-01-24                    653                       0         NaN
2020-01-25                    941                      26    0.027630
2020-01-26                   2019                      56    0.027737
2020-01-27                   2794                      80    0.028633
2020-01-28                   4588                     106    0.023104
2020-01-29                   6047                     132    0.021829
2020-01-30                   8142                     170    0.020879
2020-01-31                  11940                     259    0.021692
2020-02-01                  14557                     305    0.020952
2020-02-02                  17318                     361    0.020845

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
Date                      12 non-null datetime64[ns]
CoronavirusCasesWorld     12 non-null int64
CoronavirusDeathsWorld    12 non-null int64
Death rate                9 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 512.0 bytes


In [118]:
y = data.iloc[:,1].values
# y = y.reshape(1, -1)
y

array([  332,   555,   653,   941,  2019,  2794,  4588,  6047,  8142,
       11940, 14557, 17318])

In [124]:
X = np.arange(10)
X = X.reshape(-1, 1)
X

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [125]:
y.shape

(12,)

In [126]:
X.shape

(12, 1)

In [128]:
model = LogisticRegression(random_state=0)
model.fit(X, y)

/Users/OndrejMartinek/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/OndrejMartinek/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [140]:
x = np.arange(13,23)
x = x.reshape(-1, 1)
x

array([[13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22]])

In [141]:
model.predict(x)

array([17318, 17318, 17318, 17318, 17318, 17318, 17318, 17318, 17318,
       17318])

### Excercise

In [142]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [143]:
# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [144]:
# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [145]:
# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [146]:
print('x:', x, sep='\n')

x:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [147]:
print('y:', y, sep='\n', end='\n\n')
print('intercept:', model.intercept_)
print('coef:', model.coef_, end='\n\n')
print('p_pred:', p_pred, sep='\n', end='\n\n')
print('y_pred:', y_pred, end='\n\n')
print('score_:', score_, end='\n\n')
print('conf_m:', conf_m, sep='\n', end='\n\n')
print('report:', report, sep='\n')

y:
[0 1 0 0 1 1 1 1 1 1]

intercept: [-1.51632619]
coef: [[0.703457]]

p_pred:
[[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]

y_pred: [0 0 0 1 1 1 1 1 1 1]

score_: 0.8

conf_m:
[[2 1]
 [1 6]]

report:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10

